version: "3.7"
services:
  postgres:
    image: postgres
    container_name: firegames_bd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: firegames
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    depends_on:
      - postgres
    links:
      - postgres
  app:
    container_name: firegames_app
    image: docker-spring-boot-postgres:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/firegames
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  front-app:
    container_name: firegames_app_front
    image: node:14-alpine
    build: ./front
    environment:
      - BACK_API=http://app:8080
    ports:
      - "3000:3000"
    depends_on:
      - app
